name: Daily Execution

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser (e.g., firefox, chrome)'
        required: false
      headless_mode:
        description: 'Set headless mode (True/False)'
        required: false
      parameters:
        description: 'Parameters to be passed to behave'
        required: false     
        

jobs:
  run-e2e-tests:
    name: E2E Web Tests - Daily
    env:
      REPORT_JSON: e2e_tests_web_prod.json
    runs-on: [windows-latest]
    permissions:
      contents: read
      actions: read
    steps:
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1

      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run E2E Tests Web Prod - Firefox
        run: |
          $env:BROWSER="${{ github.event.inputs.browser }}"
          $env:HEADLESS_MODE="${{ github.event.inputs.headless_mode }}"
          behave ${{ github.event.inputs.parameters }} --tags=-xfail --format json.pretty --outfile e2e_tests_web_prod.json --format pretty

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: failed_tests_screenshots
          path: ./reports/screenshots/*.png
          retention-days: 7"

      - name: Upload test results in JSON format
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: ${{ env.REPORT_JSON }}
          path: ./e2e_tests_web_prod.json
          retention-days: 7
